name = "Blobs"
uuid = "2063b8be-a4ad-11e8-1fb9-93d01944c8ed"
authors = ["Jamie Brandon <jamie@scattered-thoughts.net>"]
version = "0.4.0"

[deps]
MacroTools = "1914dd2f-81c6-5fcd-8719-6d5c9610ff09"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
